---
- name: ensure apt cache is up to date
  become: true
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"


- name: ensure packages are installed
  apt: name={{item}} state=present
  become: true
  when: ansible_os_family == "Debian"
  with_items:
    - nginx
