---
- name: ensure apt cache is up to date
  become: true
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"


- name: ensure packages are installed
  apt: name={{item}} state=present
  become: true
  when: ansible_os_family == "Debian"
  with_items:
    - nginx

- name: Proxy to django configuration
  become: true
  template: src=templates/nginx.sites-available.todo.j2 dest=/etc/nginx/sites-available/todo
  when: ansible_os_family == "Debian"

- name: symlink to enable
  become: true
  file: src=/etc/nginx/sites-available/todo dest=/etc/nginx/sites-enabled/todo state=link
  when: ansible_os_family == "Debian"

- name: Add www-data to webapps group
  become: true
  user: name=www-data groups=webapps append=yes

- name: Restart nginx
  become: true
  service: name=nginx state=restarted
  when: ansible_os_family == "Debian"
