---
- name: Apt-Get Update
  become: true
  apt: update_cache=yes cache_valid_time=3600
  when: ansible_os_family == "Debian"

- name: Installing Supervisor
  become: true
  apt: name={{item}} state=present
  with_items:
    - supervisor
  when: ansible_os_family == "Debian"

- name: Configure for gunicorn
  become: true
  template: src=templates/supervisor.todo.conf.j2 dest=/etc/supervisor/conf.d/todo.conf
  when: ansible_os_family == "Debian"

- name: Restart Supervisorctl
  become: true
  service: name=supervisor state=restarted
  when: ansible_os_family == "Debian"
