---
- name: Create webapps group
  become: true
  group: name={{application_group}} state=present
  when: ansible_os_family == "Debian"

- name: Add User
  become: true
  user: name={{application_user}} shell=/usr/bin/zsh groups={{application_user}} append=yes home=/home/{{application_user}}
  when: ansible_os_family == "Debian"

